# Generated by Django 4.2.11 on 2024-03-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='id_product',
            field=models.IntegerField(null=True),
        ),
    ]
